url_color #522a70
active_border_color #35686B
inactive_border_color #1C1D26
foreground #ffffff
background #000000
background_opacity 1
selection_foreground none
selection_background #35686B
color0 #000000
color8 #767676
color1 #cc0403
color9 #f2201f
color2  #19cb00
color10 #23fd00
color3  #cecb00
color11 #fffd00
color4  #0d73cc
color12 #1a8fff
color5  #cb1ed1
color13 #fd28ff
color6  #0dcdcd
color14 #14ffff
color7  #dddddd
color15 #ffffff
mark1_foreground black
mark1_background #98d3cb
mark2_foreground black
mark2_background #f2dcd3
mark3_foreground black
mark3_background #f274bc
#You can set the remainig colors(color16 to color255) on your own
