-- keymaps can also be found in treesitter.lua
-- keymaps can also be found in lsp.lua
-- keymaps can also be found in code_runner.lua
-- keymaps can also be found in completions.lua
-- vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {virtual_text = false })
