#active border color
$col1 = 16161E
$col2 = 4BA4A3
$col3 = D56E89
$col4 = 16161E
#inactive border color
$col5 = 1C1D26
#active groupbar color
$col6 = d53737
#ative groupbar color when group is locked
$col7 = 922d6e
#incative groupbar color
$col8 = 8c8789

#Hyprlock color pallette

#Background image path
$image = /home/adeed/Wallpapers/abm.png
#Fallback background color
$bgc = rgba(0, 0, 0, 1.0)
#Image border color
$ibc = rgba(0, 0, 0, 1.0)
#Name text color
$ntc = rgba(0, 0, 0, 1.0)
#Time text color
$ttc = rgba(0, 0, 0, 1.0)
#Date text color
$dtc = rgba(0, 0, 0, 1.0)
#border color of input field
$bic = rgba(0, 0, 255, 1.0)
#Input field color
$ifc = rgba(0, 0, 0, 1.0)
#input text color
$itc = rgba(255, 0, 0, 1.0)
#Border color when checking password
$bcc = rgba(255, 0, 0, 1.0)
#Outer border and fail text color when authentication fails
$afc = rgba(0, 255, 0, 1.0)
