source=~/.config/hypr/color_palette.conf

general{
    hide_cursor = true
}

background{
    monitor =
    path = $image
    color = $bgc
    blur_size = 15
    blur_passes = 4
    noise = 0
    contrast = 1.5
    brightness = 1
    vibrancy = 0.1
    vibrancy_darkness = 0
}

# Profile Pic
image {
    monitor =
    path = /home/adeed/.config/hypr/resources/pfp.png
    size = 250
    rounding = -1
    
    border_size = 3
    border_color = $ibc

    halign = center
    valign = center
    position = 0, 200
}

# Name
label {
    monitor =
    text = Syed Adeed
    
    color = $ntc
    font_size = 30
    font_family = Monaspace Xenon

    halign = center
    valign = center
    position = 0, 40
}

# Input Field
input-field {
    monitor =
    size = 320, 55
    fade_on_empty = false
    hide_input = false
    rounding = -1
    fail_timeout = 1000
    fail_transition = 300
    
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    
    outline_thickness = 4
    outer_color = $bic
    inner_color = $ifc
    
    font_color = $itc
    placeholder_text = <i>Password is 1234</i>

    check_color = $bcc

    fail_color = $afc
    fail_text = Fucking idiot

    halign = center
    valign = center
    position = 0, -30
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +'%I:%M ')<span size='x-small'>$(date +'%p')</span></span>"

    color = $ttc
    font_size = 105
    font_family = steelfish outline regular

    halign = left
    valign = bottom
    position = 10, 30
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    
    color = $dtc
    font_size = 28
    font_family = Monaspace Xenon

    halign = left
    valign = bottom
    position = 10, 10
}
