monitor=,preferred,auto,auto

#exec-once = swww-daemon --format xrgb
exec = sudo xremap ~/.config/xremap/config.yml
#exec-once = kitty +kitten panel --edge=background btop

env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,23
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,23

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
    sensitivity = 0
}
